server:
  port: 15000

spring:
  cloud:
      config:
        server:
          health:
            enabled: false

          git:
            uri: https://github.com/ashishkpathak/spring.config.git

